language: node_js
sudo: false
node_js:
  - 8
  - 7
  - 6

cache:
  directories:
    - ~/.npm
    - node_modules

branches:
  only:
    - master

before_install:
  # Use exact Node version.
  - nvm use $TRAVIS_NODE_VERSION

  # Setup package managers.
  - npm set loglevel error
  - npm set progress false

script:
  - npm run test

after_script:
  - npm prune

deploy:
  provider: script
  script: npm run travis-deploy-once "npm run semantic-release"
  skip_cleanup: true
  on:
    branch: master
