language: node_js
sudo: false
node_js:
  - 7
  - 6
  - 4

cache:
  directories:
    - ~/.npm

branches:
  only:
    - master

before_install:
  # Use exact Node version.
  - nvm use $TRAVIS_NODE_VERSION

  # Setup package managers.
  - npm set loglevel error
  - npm set progress false

